# Student Profile

print("===== STUDENT PROFILE =====")
first_name = input("Enter First Name: ")
last_name = input("Enter Last Name: ")
dob = input("Enter Date of Birth (DD/MM/YYYY): ")
city = input("Enter City: ")
address = input("Enter Address: ")
age = int(input("Enter Age: "))
percentage = float(input("Enter Percentage: "))
department = input("Enter Department: ")
college_name = input("Enter College Name: ")
print("\n========== STUDENT PROFILE ==========")
print("First Name   :", first_name)
print("Last Name    :", last_name)
print("Date of Birth:", dob)
print("City         :", city)
print("Address      :", address)
print("Age          :", age)
print("Percentage   :", percentage, "%")
print("Department   :", department)
print("College Name :", college_name)
print("=====================================")